### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by DONALDBZR**
I have shown you the codes earlier!  You codes have been refactored.

### CODE REVIEW

**Comment by ShandilyaSolutions** [comment]
Donald I hage added few buttons now. Can you please add them too. Because merging your pr will remove them..

You can see that there are 2 buttons... One called About and other Github. About opens a modal and github takes user to the code repository. 

I was working on their css yesterday where I wanted to place them at the right end of the screen also making them arround 50*50px circle size. Can you help me there? Because yesterday I had a lot of talk about this in coding den server but I was unable to do so. 

I request you to please sort that out too🙏🏻🙏🏻🙏🏻

**Comment by ShandilyaSolutions** [comment]
no i didnt. I will today. I was busy in college so couldnt. Sorry for that naming. Nice to meet you Andy.

**Comment by ShandilyaSolutions** [comment]
Sorry Andy I cannot merge this one as the code you uploaded has emrging conflicts. I think this is because I have added some new things on the mainpage 

Please look into that. I could not understand what was causing those conflicts in html and css files so I reverted all the commits

**Comment by DONALDBZR** [comment]
Hello Amritanshu,
    You should have merged before pushing new commits for not causing merge conflicts.

Sincerely yours,
Andy Ewen Gaspard.
________________________________

**Pull request merged**
